const EmployeesInfo = [
    {
        id: 0,
        name: 'James Dean',
        company: 'Coca Cola',
        car: 'Yes',
        train: 'Yes',
        internet: 'No',
        requests: '15',
        status: 'active',
    },
    {
        id: 1,
        name: 'James Dean',
        company: 'Coca Cola',
        car: 'Yes',
        train: 'Yes',
        internet: 'No',
        requests: '15',
        status: 'active',
    },
    {
        id: 2,
        name: 'James Dean',
        company: 'Coca Cola',
        car: 'Yes',
        train: 'Yes',
        internet: 'No',
        requests: '15',
        status: 'active',
    },
    {
        id: 3,
        name: 'James Dean',
        company: 'Coca Cola',
        car: 'Yes',
        train: 'Yes',
        internet: 'No',
        requests: '15',
        status: 'active',
    },
    {
        id: 4,
        name: 'James Dean',
        company: 'Coca Cola',
        car: 'Yes',
        train: 'Yes',
        internet: 'No',
        requests: '15',
        status: 'active',
    },
]

export default EmployeesInfo
